export default class MessageType {
  static AUTHENTICATE = "AUTHENTICATE";
  static AUTHENTICATED = "AUTHENTICATED";

  static ROOM_CREATE = "ROOM_CREATE";
  static ROOM_LIST_SYNC = "ROOM_LIST_SYNC";
  static ROOM_JOIN = "ROOM_JOIN";
  static ROOM_SYNC = "ROOM_SYNC";
  static ROOM_PLAY = "ROOM_PLAY";
  static ROOM_PAUSE = "ROOM_PAUSE";
  static ROOM_ADD_QUEUE = "ROOM_ADD_QUEUE";
  static ROOM_PLAY_NEXT = "ROOM_PLAY_NEXT";
  static ROOM_TRACK_UPVOTE = "ROOM_TRACK_UPVOTE";
  static ROOM_TRACK_DOWNVOTE = "ROOM_TRACK_DOWNVOTE";
  static ROOM_DELETE = "ROOM_DELETE";
  static ROOM_SET_COLOR = "ROOM_SET_COLOR";
  static ROOM_CHAT_MESSAGE = "ROOM_CHAT_MESSAGE";

  static AVAILABLE_DEVICES = "AVAILABLE_DEVICES";
  static SET_ACTIVE_DEVICE = "SET_ACTIVE_DEVICE";
}
